### ISSUE TITLE
conda installation issue 

### ISSUE THREAD

**Issue by mlcoleman** [LottePronk/whokaryote#8]
I was unable to install via conda. Got the following error:
`UnsatisfiableError: The following specifications were found to be incompatible with each other:
`
(but nothing listed)

I was however able to install via github source, after modifying the numpy requirement (in setup.py) from `'numpy~=1.19.4'` to `'numpy>=1.19.4'`. But then the tiara step did not run successfully:
```
Running tiara with 1 thread...
Traceback (most recent call last):
  File "/Users/minimo/miniconda3/envs/whokaryote/bin/tiara", line 5, in <module>
    from tiara.main import main
  File "/Users/minimo/miniconda3/envs/whokaryote/lib/python3.8/site-packages/tiara/__init__.py", line 1, in <module>
    from tiara.src.transformations import TfidfWeighter
  File "/Users/minimo/miniconda3/envs/whokaryote/lib/python3.8/site-packages/tiara/src/transformations.py", line 8, in <module>
    from numba.typed import List as NumbaList
  File "/Users/minimo/miniconda3/envs/whokaryote/lib/python3.8/site-packages/numba/__init__.py", line 42, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
  File "/Users/minimo/miniconda3/envs/whokaryote/lib/python3.8/site-packages/numba/np/ufunc/__init__.py", line 3, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
  File "/Users/minimo/miniconda3/envs/whokaryote/lib/python3.8/site-packages/numba/np/ufunc/decorators.py", line 3, in <module>
    from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception
```

**Comment by franlat** [comment]
I had the same issue but found a workaround. I installed tiara first with conda: `conda install -c conda-forge tiara`, then downgraded the numpy version to 1.19.4 with `conda install -c conda-forge numpy=1.19.4` and last, I installed whokaryote as documented: `conda install -c bioconda whokaryote`. Now it works!

**Comment by erfanshekarriz** [comment]
for conda beginners, you can use a one-liner! `conda install -c conda-forge -c bioconda tiara numpy=1.19.4 whokaryote `. Make sure to create an environment pre-hand and activate it first .e.g `conda create -n whokaryote -y && conda activate whokaryote`.
